// A scrubber for mermaid's SVG output — and a deliberate, narrow bypass of the
// app's general HTML sanitizer.
//
// WHY NOT `renderEmbeddedHtml` (livePreview.ts)?
// That one is built for UNTRUSTED markup pasted into a note, so it drops every
// `<style>` element and strips EVERY `style=` attribute ("inline styles enable
// full-screen fixed overlays / UI spoofing"). Mermaid's entire visual output IS
// a scoped `<style>` block plus inline styles: routed through it a diagram
// renders as unstyled black paths on a white square. So mermaid gets its own
// pass, which keeps CSS and drops everything executable.
//
// WHY THAT IS SAFE HERE, and only here:
//   1. The markup is not user markup. It is generated by mermaid from a diagram
//      DSL — nobody hands us an `<svg>`; they hand us `graph TD; A-->B`.
//   2. Mermaid runs at `securityLevel: 'strict'` (renderer.ts), which runs its
//      own bundled DOMPurify over the output, encodes HTML inside labels and
//      disables click/interaction directives. This pass is the second net.
//   3. `flowchart: { htmlLabels: false }` keeps labels as SVG text, so the
//      `foreignObject` path is narrow (KaTeX math) rather than the norm.
//   4. The CSS that survives is confined by `contain: paint` on the widget host
//      (theme.ts `.cm-md-mermaid`), which makes the host the containing block
//      for any `position: fixed`/`absolute` descendant — so even a `themeCSS`
//      directive smuggled in by a teammate's diagram cannot build a
//      full-window overlay. The `secure` list in renderer.ts is the other half
//      of that defence; neither is dead config.
//
// If any of those four ever stops being true, this file has to be revisited.

import { isDangerousUrl } from "../urlSafety";

/** Tags that could execute or pull in code — dropped outright. */
const BLOCKED_TAGS = new Set(["SCRIPT", "IFRAME", "OBJECT", "EMBED", "LINK", "META", "BASE"]);

/**
 * Scrub a mermaid-generated SVG string: drop executable elements, `on*`
 * handlers and script-y URLs; KEEP `<style>` and `style=` (see the header).
 *
 * Parsed as `text/html` rather than `image/svg+xml`: the HTML parser namespaces
 * inline SVG correctly, never throws on a malformed fragment, and mirrors
 * `renderEmbeddedHtml`'s shape so the two read as siblings.
 */
export function sanitizeMermaidSvg(svg: string): string {
  const parsed = new DOMParser().parseFromString(svg, "text/html");
  for (const el of Array.from(parsed.querySelectorAll("*"))) {
    // Uppercase so a foreign-content (SVG) `<script>`, whose `tagName` is
    // lowercase, is caught by the same blocklist as an HTML one.
    if (BLOCKED_TAGS.has(el.tagName.toUpperCase())) {
      el.remove();
      continue;
    }
    for (const attr of Array.from(el.attributes)) {
      const name = attr.name.toLowerCase();
      if (name.startsWith("on")) {
        el.removeAttribute(attr.name);
        continue;
      }
      const isUrlAttr =
        name === "href" || name === "src" || name === "xlink:href" || name === "action";
      if (isUrlAttr && isDangerousUrl(attr.value)) el.removeAttribute(attr.name);
    }
  }
  return parsed.body.innerHTML;
}
